name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      push:
        default: false
        description: 'Update articles'
        required: true
        type: boolean

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/packages/
            ~/.cabal/store/
          key: ghc-9.6.4-${{ hashFiles('**/cabal.project', '**/*.cabal') }}
          restore-keys: ghc-9.6.4-
      - run: ghcup install ghc 9.6.4 --set
      - run: ghcup list
      - run: cabal build all
      - run: cabal run exe:hades --verbose=0 -- docs/_data/articles.json > articles.json
      - run: mkdir -p docs/_data/
      - run: python3 -m json.tool articles.json docs/_data/articles.json
      - run: TZ=America/Bogota date +'"%Y-%m-%dT%H:%M:%S%z"' > docs/_data/updated-at.json
      - name: Update articles
        if: github.event.schedule == '0 10 * * *' || github.event.inputs.push == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add docs/_data/articles.json
          git add docs/_data/updated-at.json
          git commit -m "Update articles ($(date +%F))"
          git push
